### PR TITLE
Add stylings for agSelectCellEditor

### PR DESCRIPTION
**Pull request by johnhwhite**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-ag-select-hover-style](https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-ag-select-hover-style)

**Comment by Blackbaud-TrevorBurch** [comment]
A couple things:

1. I'm not seeing the spacing that was requested in the original user story:
```
Spacing: 5px padding on each item top and bottom (10 above and below last item - show Todd this)
```

2. I think this may just have been a user story miss, but I'm seeing rounded borders inside the cell when the cell enters its editing state. Could we remove this inner border?

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-ag-select-hover-style](https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-ag-select-hover-style)

**Comment by Blackbaud-TrevorBurch** [comment]
@johnhwhite - I see the spacing change in the css; however, when manually testing this I still don't see the padding.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-ag-select-hover-style](https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-ag-select-hover-style)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-ag-select-hover-style](https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-ag-select-hover-style)

**Review by Blackbaud-ToddRoberts — APPROVED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-ag-select-hover-style](https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-ag-select-hover-style)

**Review by Blackbaud-TrevorBurch — APPROVED** [review]

**Pull request merged**
